"use client";
import Link from "next/link";
import { useState, useTransition } from "react";
type Stock = { id: string; code: string; market: string; name: string; currency: string; latestClose: number | null; latestDate: string | null; latestSyncError: string | null };
type Result = { code: string; market: string; name: string };
export function StockLibrary({ initialStocks }: { initialStocks: Stock[] }) {
  const [stocks, setStocks] = useState(initialStocks); const [query, setQuery] = useState(""); const [results, setResults] = useState<Result[]>([]); const [message, setMessage] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  const search = () => startTransition(async () => { const r = await fetch(`/api/stocks/search?q=${encodeURIComponent(query)}`); const b = await r.json() as { data?: Result[]; error?: string }; if (!r.ok) return setMessage(b.error ?? "搜索失败。"); setResults(b.data ?? []); });
  const add = (code: string) => startTransition(async () => { const r = await fetch("/api/stocks", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code }) }); const b = await r.json() as { data?: Stock; error?: string }; if (!r.ok || !b.data) return setMessage(b.error ?? "加入失败。"); setStocks((current) => [b.data!, ...current.filter((stock) => stock.id !== b.data!.id)]); setResults([]); setMessage(`${b.data.name} 已加入并完成日线同步。`); });
  return <section className="border border-border bg-card"><div className="border-b border-border p-5"><div className="flex flex-wrap gap-2"><input aria-label="股票代码或名称" value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => event.key === "Enter" && search()} placeholder="600519、腾讯、BRK-B" className="min-w-0 flex-1 border border-border bg-background px-3 py-2 text-sm" /><button onClick={search} disabled={pending} className="border border-accent bg-accent px-4 py-2 text-sm text-accent-foreground">搜索</button></div>{results.length ? <div className="mt-3 divide-y border border-border">{results.map((item) => <div key={`${item.market}:${item.code}`} className="flex items-center justify-between gap-3 p-3"><span>{item.name} <small className="font-mono text-muted-foreground">{item.code} · {item.market}</small></span><button onClick={() => add(item.code)} className="text-sm text-accent">加入</button></div>)}</div> : null}{message ? <p className="mt-3 text-sm text-muted-foreground">{message}</p> : null}</div><div className="divide-y divide-border">{stocks.map((stock) => <article key={stock.id} className="flex items-center justify-between gap-3 p-5"><div><Link href={`/stocks/${stock.id}`} className="font-semibold hover:text-accent">{stock.name}</Link><p className="mt-1 font-mono text-xs text-muted-foreground">{stock.code} · {stock.market} · {stock.latestDate?.slice(0, 10) ?? "尚未同步"}</p></div><p className="font-mono text-sm">{stock.latestClose?.toFixed(2) ?? "--"} {stock.currency}</p></article>)}{!stocks.length ? <p className="p-10 text-center text-sm text-muted-foreground">股票库为空。请先搜索并加入中美港股票。</p> : null}</div></section>;
}
